name: EventLogs-CI/CD-Pipeline

on: [ push ]

jobs:
  build-test-and-deploy-if-master:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Git-Repo
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'
        cache: 'npm'

    - name: Setup Chrome
      uses: browser-actions/setup-chrome@latest

    - name: Install NPM-Dependencies
      run: npm ci

    - name: Run linters
      uses: wearerequired/lint-action@v2
      with:
        eslint: true
        prettier: true
        prettier_extensions: ts,html
        prettier_auto_fix: false

    - name: Run Karma tests headless
      run: npm run github-actions-test

    - name: Build Angular project
      run: npm run github-actions-build

    - name: Deploy to Github Pages if branch is master
      if: ${{ github.ref == 'refs/heads/master' }}
      uses: peaceiris/actions-gh-pages@v3
      with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          enable_jekyll: true
